### ISSUE TITLE
UG review

### ISSUE THREAD

**Issue by ExtraShotLatte** [AY2223S2-CS2103T-T11-3/tp#112]

**Comment by glozxi** [comment]
Todo: add `find`, `exit`, `help`, `clear` to UG

**Comment by ExtraShotLatte** [comment]
Had a few question in mind, these questions are a duplicate of the questions i asked in PR #151

1. Should we sort the UG in lexicographic order? (Alternatively, we could prioritise a few important commands for the user experience such as the `clear`, `newcontact` and `newevent` command, especially for first time users)
2. Let's include warning for the `clear` command as it is a destructive command that could wipe out the user's data
3. Let's include some form of starting guide in the message area for first time users to look at? For example:
![Screenshot 2023-03-27 at 1 29 43 AM](https://user-images.githubusercontent.com/58366602/227793488-fb9e43a3-79ca-4d01-9ba5-b8d4ad786d6a.png)

**Comment by ExtraShotLatte** [comment]
UG review done, will proceed with closing Issue.
