### ISSUE TITLE
Test jar file

### ISSUE THREAD

**Issue by glozxi** [AY2223S2-CS2103T-T11-3/tp#136]
Ensure that the jar file works as expected in an empty folder and using Java 11, by doing some manual testing.
- [x] Mac
- [x] Windows
- [x] Linux

**Comment by ExtraShotLatte** [comment]
Jar file released is [here](https://github.com/AY2223S2-CS2103T-T11-3/tp/releases/tag/v.1.2.1).

**Comment by ExtraShotLatte** [comment]
Tested working on Windows machine as seen in SS below.
![image](https://user-images.githubusercontent.com/58366602/226820137-51905095-c019-41cc-beff-ad2097973025.png)

**Comment by glozxi** [comment]
On Linux, saves are not in the data folder unless file paths in  `preferences.json` are changed. Windows uses `\\` but Linux uses `/` in file paths.

**Comment by ExtraShotLatte** [comment]
Tested working on M2 MacOS as well.

![image](https://user-images.githubusercontent.com/58366602/227008038-6ea9863b-f836-409a-bef3-d5dbfdaef308.png)

**Comment by ExtraShotLatte** [comment]
Since the jar tested working on all 3 major OS / distributions, will proceed to close Issue!
