### ISSUE TITLE
[PE-D][Tester A] remind command returns 0 events when there is an event that will be happening after today's date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-3/tp#208]
### Sample Event
![image.png](https://raw.githubusercontent.com/Acerizm/ped/main/files/0b791227-b25b-45eb-91b4-4916614bedeb.png)

### Outcome of `remind` command
![image.png](https://raw.githubusercontent.com/Acerizm/ped/main/files/0e487f8e-54e6-4fa1-a361-f9f8fca9fbaa.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Acerizm/ped#4

**Comment by engenhui1999** [comment]
This event is ongoing, not an event to be reminded. Not a bug but a feature.
