### ISSUE TITLE
[PE-D][Tester B] Duplicate contacts not handled well by the system

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-3/tp#209]
## Description
Editing the saved data file directly to have duplicate phone contacts in their phone numbers. The application loads with events but not with the contact lists. However, the event still has the contact information which is not expected.

## Steps to Reproduce
1. Add any two contacts
2. Close the application
3. Open `data/contactlist.json` with a text editor
4. Edit the 2nd contact's phone number to match the first contact's. 
5. Save and close the text editor
5. Open the application

## Expected Outcomes
The contact in the event should not exist since a contact does not exist when the whole contact list is empty due to an error in loading the saved file

## Images

![image.png](https://raw.githubusercontent.com/Junyi00/ped/main/files/323dbb22-d513-4319-b67a-cc725aa23e7a.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Junyi00/ped#6

**Comment by engenhui1999** [comment]
Not legitimate use case as user is supposed to edit the data file.
