### ISSUE TITLE
[PE-D][Tester D] Not able to handle long names entered in Paidlancers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-3/tp#210]
Long strings of names entered are simply displayed as ... as trailing dots, making it unable for users to read the full name. 

![image.png](https://raw.githubusercontent.com/kayyenl/ped/main/files/e297a4ea-d2a5-473a-993f-01eafab2cbe5.png)

Perhaps word-wrapping could be done to ensure visibility of such names, so that it can be still displayed to the user if he/she need such details. Or if long names are not desirable, a prompt could be provided to get the user to reduce the name to a shorter one.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: kayyenl/ped#6

**Comment by engenhui1999** [comment]
Duplicate issue as #193
