### ISSUE TITLE
[PE-D][Tester D] Revenue function does not work on high integers of revenue, although accepted into the app.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-3/tp#213]
![image.png](https://raw.githubusercontent.com/kayyenl/ped/main/files/90fc9f72-730e-4138-8f85-e15cb0adf0d1.png)

Perhaps some form of type conversions can be available, to ensure the functionality persists even with high values of rates.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kayyenl/ped#7

**Comment by engenhui1999** [comment]
Wrong intended usage as user did not mark any events as done.
