### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by glozxi** [AY2223S2-CS2103T-T11-3/tp#23]
- [x] Add a UI mockup of your intended final product. 
- [x] Update all contents to match your own project.
- [x] Update the link of the GitHub Actions build status badge (Build Status) so that it reflects the build status of your team repo.
- [x] Acknowledge the original source of the code e.g.,This project is based on the AddressBook-Level3 project created by the [SE-EDU initiative](https://se-education.org).

**Comment by ExtraShotLatte** [comment]
Github actions build status badge is already done, will do the update of content and acknowledgement today!
